= GeoTIFF 1.1 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies the conformance of the implementation
under test (IUT) with respect to the OGC GeoTIFF 1.1 Standard. Conformance testing is a kind of "black box" testing that examines the externally visible characteristics or behaviors of the IUT while disregarding
any implementation details.

The GeoTIFF format is used throughout the geospatial and earth science communities to share geographic image data. The OGC GeoTIFF standard defines the Geographic Tagged Image File Format (GeoTIFF) by specifying requirements and encoding rules for using the Tagged Image File Format (TIFF) for the exchange of georeferenced or geocoded imagery. The OGC GeoTIFF 1.1 standard formalizes the existing community GeoTIFF specification version 1.0 and aligns it with the continuing addition of data to the EPSG Geodetic Parameter Dataset.



Several conformance classes are defined in the principal specifications; the ones
listed below are covered by this test suite:

* A.2. Conformance Class TIFF
* A.3. Conformance Class Raster2Model_CoordinateTransformation_GeoKey

== Test requirements

The document listed below stipulates requirements that must be satisfied by a 
conforming implementation.

1. http://docs.opengeospatial.org/is/19-008r4/19-008r4.html[OGC 19-008r4, OGC GeoTIFF Standard 1.1]


== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.geotiff11`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Tiff Tests
|org.opengis.cite.geotiff11.tiffTests.*

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These are summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|iut
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|ics
|A comma-separated list of string values.
|O
|An implementation conformance statement that indicates which conformance classes or options are supported.

|===
